# PIPEDRIVE
PIPEDRIVE_COMPANE_NAME = 'XXXXXXXX'
PIPEDRIVE_API_TOKEN = 'XXXXXXXX'
PIPEDRIVE_LINKEDIN_PERSONFIELD_NAME = 'LinkedIn'

# PROSPECTIN
PROSPECTIN_API_TOKEN = 'XXXXXXXX'
PROSPECTIN_CURRENT_CAMPAIN = 'XXXXXXXX'
